CREATE TABLE task (
  id VARCHAR PRIMARY KEY,
  title VARCHAR NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_end BOOLEAN DEFAULT FALSE
);

CREATE TABLE tag (
  id VARCHAR PRIMARY KEY,
  name VARCHAR NOT NULL
);